version: '3'
services:
  web:
    image: osiolabs/drupaldevwithdocker-php:7.2
    volumes:
      - ./docroot:/var/www/drupal
      - ./vendor:/var/www/vendors
    env_file:
      - ./docker.env
    ports:
      - "80:80"
      - "443:443"
  db:
    image: osiolabs/drupaldevwithdocker-mysql:10.0
    volumes:
      - ./db-backups:/var/mysql/backups:delegated
    env_file:
      - ./docker.env
    ports:
      - "3306:3306"
  pma:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./docker.env
    ports:
     - "8001:80"